import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './Components/Navbar'
import Navigationbar from './Components/Navigationbar';
import { ShopContextProvider } from './context/shop-context';
import 'bootstrap/dist/css/bootstrap.min.css';
import {AuthProvider} from './context/authContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ShopContextProvider>
            <Navigationbar />
            {children}
          </ShopContextProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
